### ISSUE TITLE
体验报告

### ISSUE THREAD

**Issue by MOONLIGHTV** [akrisrn/u-no-u.no#3]
1.header的底边模糊了，还以为撸多了
2.图片很突兀的就蹦出来了，加载之前没有占位。
3.akrisrn是啥玩意，不是蠢锅么？
4.Lorem 就一条，用Ul>LI干毛？倒是导航是H6下面一堆a，而且位置也不醒目
5.PRERENDER MODE下页面切换之间没有跳转动画

**Comment by akrisrn** [comment]
1. 已经改好
2. 有 loading 动画，骨架屏占位效果我不太满意
4. index 是由 markdown 渲染来的，布局就是这样
5. 预渲染后不存在 vue 节点，也无法应用路由跳转动画

感谢反馈。
